### ISSUE TITLE
Neovim Crashes On Open

### ISSUE THREAD

**Issue by alivefromupstairs** [bakkeby/st-flexipatch#1] opened 2019-11-21 01:24 UTC
### Steps to produce:
  - clone this repo
  - `# make install`
  - `$ nvim`

`$ nvim` outputs this to stdout:
```
ABORT: lookup_next within a TYPE_KEY node
zsh: abort (core dumped)  nvim
```
`$ env -i TERM=ansi-256color "$(which nvim)"` runs `nvim` successfully though. `$ nvim` runs normal on a fresh `st` clone.

**Comment by bakkeby** [comment] 2019-11-21 09:21
You are right. This is apparently an issue with the libtermkey library according to https://github.com/neovim/neovim/issues/5895, but is reproduced by applying the [delkey](https://st.suckless.org/patches/delkey/) patch.

I had once tried out this patch, but turns out I had only partially removed it as I still had changes in st.info.

I have committed a fix for this now:
https://github.com/bakkeby/st-flexipatch/commit/e76c4c0637a0a57adc562ccad7a80fcecee8f22d

Thanks for reporting.

**Closed by bakkeby** 2019-11-21 09:21 UTC
